#!/bin/bash                                                                                                                                    

# Request a run time of 5 hours and 30 minutes                                                                                                
#PBS -l walltime=68:30:00                                                                                                                      

# Request 1 processor in 1 node                                                                                                               
#PBS -l nodes=1:ppn=12         
                                                                                                                
# Request 7600 megabytes memory per processor.  ( 48 usable CPUs)                                                                             
#PBS -l mem=88gb                                                                                                                              
#PBS -j oe                                                                                                                                    
#PBS -N rnaseqd1_alignment                                                                                                                    
#PBS -q copperhead                                                                                                                            
#PBS -t 1-30                                                                                                                                  
umask 007
set -eu

file=$(sed -n -e "${PBS_ARRAYID}p" /nobackup/banana_genome/aneeta/RNAseqdata2_D1/pairs.txt)

#echo "Launching samtools"

#cd $home                                                                                                                                     
#module load cutadapt                                                                                                                         
#module load fastqc                                                                                                                           
#module load trim_galore                                                                                                                      
module load samtools

export PATH="$HOME/sw/hisat2-2.1.0:$PATH"

cd /nobackup/banana_genome/aneeta/RNAseqdata2_D1/aligned

#~/sw/ExpressionAnalysis-ea-utils-bd148d4/clipper/                                                                                             
echo "Working on ${file}"
hisat2 -p 8 --dta -x /users/auppal/sw/hisat2-2.1.0/human_index -1 /nobackup/banana_genome/aneeta/RNAseqdata2_D1/trimmed/${file}_R1_val_1.fq -2 /nobackup/banana_genome/aneeta/RNAseqdata2_D1/trimmed/${file}_R2_val_2.fq -S ${file}_rnaseqD1hisat.sam                       
